name: Newman Tests

on:
  push:
    branches:
      - main

jobs:
  newman:
    name: Run Newman Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: npm install newman newman-reporter-htmlextra
      
    - name: Run Newman test
      run: newman run ./api-test/Demo-API-Flow.postman_collection.json -r htmlextra --reporter-htmlextra-export ./newman/report.html
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: newman-report
        path: ./newman/report.html
        retention-days: 30
